### ISSUE TITLE
Firefox WebExtensions API

### ISSUE THREAD

**Issue by ttuygun** [mauricelam/ScrollMaps#14]
Could you port the extension to Firefox using [WebExtentions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)?

**Comment by andreicristianpetcu** [comment]
Please port it to Firefox. Most extensions are trivial to port https://vimeo.com/241435808

**Comment by ttuygun** [comment]
I ported successfully to WebExtension ready codebase without any error.

**Comment by ttuygun** [comment]
https://github.com/mauricelam/ScrollMaps/pull/34
