### ISSUE TITLE
YouTube Autocomplete not working after installing ScrollMaps

### ISSUE THREAD

**Issue by celento** [mauricelam/ScrollMaps#18]
For some strange reasons, the YouTube autocomplete feature is not working after installing this extension. Works fine on disabling the extension. 

OS : MacOS Mojave
Chrome Version : Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by mauricelam** [comment]
Sorry for the delayed reply. I checked and this no longer happens in version 2.8.0
