### ISSUE TITLE
Safari 7.0 support

### ISSUE THREAD

**Issue by jimothyGator** [mauricelam/ScrollMaps#2]
ScrollMaps doesn't seem to work on Safari 7 on Mavericks. It does disable zooming, which is fantastic (what was Google thinking?), but scrolling doesn't work. Neither horizontal (east-west) nor vertical (north-south) scrolling works. 

When scrolling (with two fingers on a trackpad; presumably also with a scroll wheel or Magic Mouse), the cursor changes to the four arrows cursor, but the map does not scroll.

**Comment by mauricelam** [comment]
Sorry Apple decided that extension developers have to pay their membership fee in order to continue publishing extensions for Safari. It's not worth it for me to continue developing on their platform.

I continue to use, and so will continue to update, the Chrome extension.
