### ISSUE TITLE
Feature Request: Two finger rotation to rotate the map

### ISSUE THREAD

**Issue by porg** [mauricelam/ScrollMaps#20]
First thanks for providing this great software free of charge! Great to use scrolling to move over the map and pinching to zoom. Feels already quite Mac native!

To complete the Mac UX rotating with two finger for rotating the map would be wonderful! If the rotation gesture seamlessly interplays with the pinching gesture such as in Apple Maps then it would even be top notch!

**Comment by mauricelam** [comment]
I would love to be able to do that too! Unfortunately, there are no browser APIs that Chrome exposes that would allow the extension to get trackpad rotation gestures.
It was proposed to w3c but was rejected: https://github.com/w3c/pointerevents/issues/206

**Comment by porg** [comment]
Thanks for the consideration and the explanation why the implementation is not possible.

I commented at w3c/pointerevents#206 to @patrickhlauke to consider this very issue here specifically and web apps with more complex gestures in general, especially 3D web apps, as valid use cases.
