### ISSUE TITLE
Maps results redirected from Google Search do not work 

### ISSUE THREAD

**Issue by ttuygun** [mauricelam/ScrollMaps#23]
1. [Make](https://www.google.com/search?&q=restaurants+in+amsterdam) a Google Search like "restaurants in amsterdam"
2. Results [redirects](https://www.google.com/search?q=restaurants%20in%20amsterdam&npsic=0&rflfq=1&rlha=0&rllag=52359089,4890506,1216&tbm=lcl&rldimm=7582517631839791706&lqi=ChhyZXN0YXVyYW50cyBpbiBhbXN0ZXJkYW1aJwoLcmVzdGF1cmFudHMiGHJlc3RhdXJhbnRzIGluIGFtc3RlcmRhbQ&phdesc=fsg0Cd9jYPg&ved=2ahUKEwjd546tmfvmAhWRwAIHHQdcC-oQvS4wAHoECAsQIA&rldoc=1&tbs=lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9&rlst=f#rlfi=hd:;si:7582517631839791706,l,ChhyZXN0YXVyYW50cyBpbiBhbXN0ZXJkYW1aJwoLcmVzdGF1cmFudHMiGHJlc3RhdXJhbnRzIGluIGFtc3RlcmRhbQ,y,fsg0Cd9jYPg;mv:[[52.3824501,4.9350141999999995],[52.3468567,4.846763600000001]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9) an Google Maps Results page 
3. ScrollMaps functionality do not work in [this](https://www.google.com/search?q=restaurants%20in%20amsterdam&npsic=0&rflfq=1&rlha=0&rllag=52359089,4890506,1216&tbm=lcl&rldimm=7582517631839791706&lqi=ChhyZXN0YXVyYW50cyBpbiBhbXN0ZXJkYW1aJwoLcmVzdGF1cmFudHMiGHJlc3RhdXJhbnRzIGluIGFtc3RlcmRhbQ&phdesc=fsg0Cd9jYPg&ved=2ahUKEwjd546tmfvmAhWRwAIHHQdcC-oQvS4wAHoECAsQIA&rldoc=1&tbs=lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9&rlst=f#rlfi=hd:;si:7582517631839791706,l,ChhyZXN0YXVyYW50cyBpbiBhbXN0ZXJkYW1aJwoLcmVzdGF1cmFudHMiGHJlc3RhdXJhbnRzIGluIGFtc3RlcmRhbQ,y,fsg0Cd9jYPg;mv:[[52.3824501,4.9350141999999995],[52.3468567,4.846763600000001]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9) page. 

![image](https://user-images.githubusercontent.com/10091984/72202027-c507f700-346b-11ea-997e-9b686e4e75d8.png)

**Comment by mauricelam** [comment]
Thanks for the report. This was fixed in v2.9.0, which I just submitted to the Chrome web store. It's under review by them for permission issues, and will be published automatically once it's reviewed.
