### ISSUE TITLE
not working for Leaflet

### ISSUE THREAD

**Issue by BartmanEH** [mauricelam/ScrollMaps#27]
Can you make this work for Leaflet based maps using OpenStreetMaps? e.g. [https://leafletjs.com/examples/quick-start/](https://leafletjs.com/examples/quick-start/)

**Comment by mauricelam** [comment]
This is long overdue, but I've finally implemented this in v5.0.0

**Comment by BartmanEH** [comment]
Thank you. Oof, it's been so long, I can't remember what project I was working on that needed this :-)
