### ISSUE TITLE
Points of interest not showing up on embedded maps?

### ISSUE THREAD

**Issue by peanutismint** [mauricelam/ScrollMaps#3]
Chrome 36.0.1985.8: On some embedded maps, activating ScrollMaps seems to cause places of interest not to draw/appear. For instance, on the Parkopedia website, when ScrollMaps is engaged, none of the car parks icons seem to show.  

Other than that, great! :-)

**Comment by mauricelam** [comment]
The issue with Parkopedia website is fixed on version 2.0
