### ISSUE TITLE
support for sites using mapbox like strava.com

### ISSUE THREAD

**Issue by arkarkark** [mauricelam/ScrollMaps#33]
This might be out of the scope of your project but strava.com uses mapbox maps ([example](https://www.strava.com/activities/much-easier-112-mile-ride-than-expected-5386465808)) and I sure do miss ScrollMaps functionality there. They have a [five year old issue](https://github.com/mapbox/mapbox-gl-js/issues/2618) to add support with some example code.

**Comment by mauricelam** [comment]
This is (finally) implemented this in v5.0.1

**Comment by arkarkark** [comment]
amazing! thank you! it works great.
