### ISSUE TITLE
Zoom speed is super fast and very difficult to control

### ISSUE THREAD

**Issue by fes3507** [mauricelam/ScrollMaps#37]
I use M1 Mac mini with Magic Trackpad 2. ScrollMaps works great except zooming when I do pinching, it zooms super fast and very difficult to adjust the zoom level I want. In config page, there are zooming speed adjust control but it only applies to map embedded page, not google maps pages. It would be great if you could either fix this zoom speed or make it adjustable in config page.

**Comment by mauricelam** [comment]
Thanks for reporting the problem. What URL were you running on, where the zooming is super fast?

**Comment by fes3507** [comment]
Hello @mauricelam, Thank you for your reply. URL was https://www.google.com/maps 
Please let me know if you need any extra information for you to reproduce the issue.

**Comment by fes3507** [comment]
Hi @mauricelam, Thank you for the quick fix! I think you released 3.3 in GitHub but chrome store still shows 3.2. Will it be released in chrome store soon?

**Comment by mauricelam** [comment]
I submitted version 3.4.0 to the Chrome web store, which should include this fix. 3.3.0 was created earlier but I did not submit it to the store; sorry for the confusion.
