### ISSUE TITLE
Uploading to AMO

### ISSUE THREAD

**Issue by ttuygun** [mauricelam/ScrollMaps#38]
Can you upload extension to AMO (https://addons.mozilla.org)?

@mauricelam

**Comment by mauricelam** [comment]
Yes, I have uploaded the extension addons.mozilla.org, and it's undergoing review now

**Comment by mauricelam** [comment]
Version 3.4.0 is now live on https://addons.mozilla.org/en-US/firefox/addon/scrollmaps/
