### ISSUE TITLE
support for earthstar graphics esri sites like tsunami.gov

### ISSUE THREAD

**Issue by arkarkark** [mauricelam/ScrollMaps#68]
It'd be neat if this extension worked on sites like https://www.tsunami.gov/
looks like they use "earthstar graphics"  powered by esri

**Comment by mauricelam** [comment]
This is fixed by https://github.com/mauricelam/ScrollMaps/commit/646e88a04a3d27eab5faaf5a6288d11945b82003, which is available in v5.0.3. Thanks for reporting!

**Comment by arkarkark** [comment]
confirmed! works great! thanks so much
